server:
  port: 8008

spring:
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-container:3306/middleware #Uncomment to use it on FT1
    #url: jdbc:mariadb://localhost:3306/middleware  #Uncomment to use it in local environment
    username: root
    password: root
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
